name = "wumpus"
version = "0.1.0"
license = "MIT"
author = "Matthew MacGregor"
maintainer = "m.macgregor@gmail.com"
copyright = "Copyright 2022-2024, Matthew MacGregor"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
